using System.Text;
using DotnetContainerizer.Model;
using DotnetContainerizer.Scanning;

namespace DotnetContainerizer.Generation;

/// <summary>
/// Writes an Azure DevOps pipeline that builds a container image for every containerizable project
/// and pushes it to Azure Container Registry, plus the job template the pipeline uses.
/// </summary>
internal static class AzurePipelineGenerator
{
    public const string PipelineFileName = "azure-pipelines.yml";
    public const string TemplateFolder = ".azuredevops/templates";
    public const string BuildTemplateFileName = "build-image.yml";
    public const string DeployTemplateFileName = "helm-deploy.yml";

    /// <summary>Name of the job that builds, tests and audits before any image is built.</summary>
    public const string ValidateJobName = "Validate";

    public static IEnumerable<GeneratedFile> Generate(ScanResult scan, GenerationSettings settings)
    {
        yield return new GeneratedFile(Path.Combine(scan.RepositoryRoot, PipelineFileName), Pipeline(scan, settings));
        yield return new GeneratedFile(
            Path.Combine(scan.RepositoryRoot, TemplateFolder.Replace('/', Path.DirectorySeparatorChar), BuildTemplateFileName),
            BuildTemplate());

        if (settings.IncludeHelm)
        {
            yield return new GeneratedFile(
                Path.Combine(scan.RepositoryRoot, TemplateFolder.Replace('/', Path.DirectorySeparatorChar), DeployTemplateFileName),
                DeployTemplate());
        }
    }

    private static string Pipeline(ScanResult scan, GenerationSettings settings)
    {
        var hasTests = scan.Projects.Any(static project => project.IsTestProject);

        // Every framework version in the solution needs its own SDK on the agent, and they have to be
        // compared as numbers: ordering "10.0" and "8.0" as text puts the wrong one first.
        var sdkVersions = scan.Projects
            .Where(static project => project.FrameworkVersion is not null)
            .Select(static project => (Major: project.FrameworkMajorVersion, Version: project.FrameworkVersion!))
            .DistinctBy(static framework => framework.Version)
            .OrderBy(static framework => framework.Major)
            .Select(static framework => framework.Version)
            .ToList();

        if (sdkVersions.Count == 0)
        {
            sdkVersions.Add("8.0");
        }

        var validate = hasTests || settings.Hardened;

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by dotnet-containerize.");
        builder.AppendLine($"# Builds every containerizable project of {scan.Name} into a container image");
        builder.AppendLine("# and pushes it to Azure Container Registry.");
        builder.AppendLine("#");
        builder.AppendLine("# Before the first run, create a Docker Registry service connection in");
        builder.AppendLine("# Project settings -> Service connections that points to your registry and");
        builder.AppendLine("# set 'dockerRegistryServiceConnection' and 'containerRegistry' below.");
        builder.AppendLine();
        builder.AppendLine("trigger:");
        builder.AppendLine("  branches:");
        builder.AppendLine("    include:");
        builder.AppendLine("      - main");
        builder.AppendLine();
        builder.AppendLine("pr:");
        builder.AppendLine("  branches:");
        builder.AppendLine("    include:");
        builder.AppendLine("      - main");
        builder.AppendLine();
        builder.AppendLine("variables:");
        builder.AppendLine($"  dockerRegistryServiceConnection: '{settings.ServiceConnection}'");
        builder.AppendLine($"  containerRegistry: '{settings.Registry}'");
        builder.AppendLine($"  imagePrefix: '{settings.ImagePrefix}'");
        builder.AppendLine("  tag: '$(Build.BuildNumber)'");
        builder.AppendLine($"  vmImageName: '{settings.VmImage}'");
        builder.AppendLine("  buildConfiguration: 'Release'");
        builder.AppendLine($"  dotnetVersion: '{sdkVersions[^1]}.x'");
        if (settings.IncludeHelm)
        {
            builder.AppendLine($"  kubernetesServiceConnection: '{settings.KubernetesServiceConnection}'");
            builder.AppendLine($"  kubernetesNamespace: '{settings.Namespace}'");
            builder.AppendLine($"  helmChartPath: '{HelmChartGenerator.ChartFolder}/{settings.ChartName}'");
            builder.AppendLine($"  helmReleaseName: '{settings.ChartName}'");
        }
        builder.AppendLine();
        builder.AppendLine("stages:");
        builder.AppendLine("  - stage: Build");
        builder.AppendLine("    displayName: Build and push container images");
        builder.AppendLine("    jobs:");

        if (validate)
        {
            builder.AppendLine($"      - job: {ValidateJobName}");
            builder.AppendLine("        displayName: Build, test and audit the solution");
            builder.AppendLine("        pool:");
            builder.AppendLine("          vmImage: $(vmImageName)");
            builder.AppendLine("        steps:");
            foreach (var version in sdkVersions)
            {
                builder.AppendLine("          - task: UseDotNet@2");
                builder.AppendLine($"            displayName: Install the .NET {version} SDK");
                builder.AppendLine("            inputs:");
                builder.AppendLine("              packageType: sdk");
                builder.AppendLine($"              version: {version}.x");
            }

            if (hasTests)
            {
                builder.AppendLine("          - task: DotNetCoreCLI@2");
                builder.AppendLine("            displayName: dotnet test");
                builder.AppendLine("            inputs:");
                builder.AppendLine("              command: test");
                builder.AppendLine($"              projects: '{TestProjectPattern(scan)}'");
                builder.AppendLine("              arguments: '--configuration $(buildConfiguration)'");
            }

            if (settings.Hardened)
            {
                AppendPackageAudit(builder, scan, settings);
            }

            builder.AppendLine();
        }

        foreach (var project in scan.Containerizable)
        {
            builder.AppendLine($"      - template: {TemplateFolder}/{BuildTemplateFileName}");
            builder.AppendLine("        parameters:");
            builder.AppendLine($"          name: {JobName(project)}");
            builder.AppendLine($"          displayName: {project.Name}");
            builder.AppendLine($"          repository: $(imagePrefix)/{project.ComponentName}");
            builder.AppendLine($"          dockerfile: {DockerfileRelativePath(project, scan)}");
            builder.AppendLine($"          buildContext: {BuildContext(scan)}");
            if (validate)
            {
                builder.AppendLine("          dependsOn:");
                builder.AppendLine($"            - {ValidateJobName}");
            }

            builder.AppendLine();
        }

        if (settings.IncludeHelm)
        {
            builder.AppendLine("  - stage: Deploy");
            builder.AppendLine("    displayName: Deploy with Helm");
            builder.AppendLine("    dependsOn: Build");
            builder.AppendLine("    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))");
            builder.AppendLine("    jobs:");
            builder.AppendLine($"      - template: {TemplateFolder}/{DeployTemplateFileName}");
            builder.AppendLine("        parameters:");
            builder.AppendLine($"          environment: {settings.ChartName}");
            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static string DeployTemplate() => """
        # Generated by dotnet-containerize.
        # Deploys every component of the solution with a single Helm release.
        # The image tag built by the Build stage is passed in with --set image.tag.

        parameters:
          - name: environment
            type: string
          - name: name
            type: string
            default: deploy

        jobs:
          - deployment: ${{ parameters.name }}
            displayName: helm upgrade
            environment: ${{ parameters.environment }}
            pool:
              vmImage: $(vmImageName)
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self

                    - task: HelmInstaller@1
                      displayName: Install Helm
                      inputs:
                        helmVersionToInstall: latest

                    - task: HelmDeploy@0
                      displayName: helm upgrade $(helmReleaseName)
                      inputs:
                        connectionType: Kubernetes Service Connection
                        kubernetesServiceConnection: $(kubernetesServiceConnection)
                        namespace: $(kubernetesNamespace)
                        command: upgrade
                        chartType: FilePath
                        chartPath: $(Build.SourcesDirectory)/$(helmChartPath)
                        releaseName: $(helmReleaseName)
                        install: true
                        waitForExecution: true
                        arguments: >-
                          --create-namespace
                          --set image.registry=$(containerRegistry)
                          --set image.prefix=$(imagePrefix)
                          --set image.tag=$(tag)

        """;

    private static string BuildTemplate() => """
        # Generated by dotnet-containerize.
        # Builds a single project into a container image and pushes it to Azure Container Registry.
        # The image is only pushed for builds of the default branch, pull request builds stop at the build.

        parameters:
          - name: name
            type: string
          - name: displayName
            type: string
          - name: repository
            type: string
          - name: dockerfile
            type: string
          - name: buildContext
            type: string
            default: '.'
          - name: dependsOn
            type: object
            default: []

        jobs:
          - job: ${{ parameters.name }}
            displayName: ${{ parameters.displayName }}
            dependsOn: ${{ parameters.dependsOn }}
            pool:
              vmImage: $(vmImageName)
            steps:
              - task: Docker@2
                displayName: Build ${{ parameters.repository }}
                condition: eq(variables['Build.Reason'], 'PullRequest')
                inputs:
                  command: build
                  repository: ${{ parameters.repository }}
                  dockerfile: ${{ parameters.dockerfile }}
                  buildContext: ${{ parameters.buildContext }}
                  containerRegistry: $(dockerRegistryServiceConnection)
                  tags: |
                    $(tag)

              - task: Docker@2
                displayName: Build and push ${{ parameters.repository }}
                condition: ne(variables['Build.Reason'], 'PullRequest')
                inputs:
                  command: buildAndPush
                  repository: ${{ parameters.repository }}
                  dockerfile: ${{ parameters.dockerfile }}
                  buildContext: ${{ parameters.buildContext }}
                  containerRegistry: $(dockerRegistryServiceConnection)
                  tags: |
                    $(tag)
                    latest

        """;

    /// <summary>
    /// Fails the build when a direct or transitive NuGet package has a known vulnerability. The
    /// dotnet CLI reports them on stdout and still exits with zero, so the output has to be inspected.
    /// </summary>
    private static void AppendPackageAudit(StringBuilder builder, ScanResult scan, GenerationSettings settings)
    {
        var target = TestProjectPattern(scan);
        if (settings.Os == ContainerOs.Windows)
        {
            builder.AppendLine("          - powershell: |");
            builder.AppendLine($"              dotnet restore {target}");
            builder.AppendLine($"              $report = dotnet list {target} package --vulnerable --include-transitive | Out-String");
            builder.AppendLine("              Write-Host $report");
            builder.AppendLine("              if ($report -match 'has the following vulnerable packages') {");
            builder.AppendLine("                Write-Error 'Vulnerable NuGet packages found.'");
            builder.AppendLine("                exit 1");
            builder.AppendLine("              }");
            builder.AppendLine("            displayName: Audit NuGet packages for known vulnerabilities");
            return;
        }

        builder.AppendLine("          - bash: |");
        builder.AppendLine("              set -euo pipefail");
        builder.AppendLine($"              dotnet restore {target}");
        builder.AppendLine($"              dotnet list {target} package --vulnerable --include-transitive | tee audit.log");
        builder.AppendLine("              if grep -q 'has the following vulnerable packages' audit.log; then");
        builder.AppendLine("                echo 'Vulnerable NuGet packages found.'");
        builder.AppendLine("                exit 1");
        builder.AppendLine("              fi");
        builder.AppendLine("            displayName: Audit NuGet packages for known vulnerabilities");
    }

    /// <summary>Azure DevOps job names allow letters, digits and underscores only.</summary>
    internal static string JobName(ProjectInfo project) =>
        "build_" + project.ComponentName.Replace('-', '_');

    /// <summary>Pipeline paths are relative to the repository root, that is where the agent checks out.</summary>
    private static string DockerfileRelativePath(ProjectInfo project, ScanResult scan) =>
        Paths.RelativeTo(scan.RepositoryRoot, DockerfileGenerator.DockerfilePath(project));

    /// <summary>The Docker build context, as a path below the checkout folder.</summary>
    internal static string BuildContext(ScanResult scan) =>
        Paths.RelativeTo(scan.RepositoryRoot, scan.ContextRoot) is var relative && relative == "."
            ? "$(Build.SourcesDirectory)"
            : $"$(Build.SourcesDirectory)/{relative}";

    private static string TestProjectPattern(ScanResult scan) =>
        scan.PrimarySolutionPath is { } solution
            ? Paths.RelativeTo(scan.RepositoryRoot, solution)
            : "**/*Tests/*.csproj";
}
