using System.Text;
using DotnetContainerizer.Model;
using DotnetContainerizer.Scanning;

namespace DotnetContainerizer.Generation;

/// <summary>
/// Writes an Azure DevOps pipeline that builds a container image for every containerizable project
/// and pushes it to Azure Container Registry, plus the job template the pipeline uses.
/// </summary>
internal static class AzurePipelineGenerator
{
    public const string PipelineFileName = "azure-pipelines.yml";
    public const string TemplateFolder = ".azuredevops/templates";
    public const string BuildTemplateFileName = "build-image.yml";

    public static IEnumerable<GeneratedFile> Generate(ScanResult scan, GenerationSettings settings)
    {
        yield return new GeneratedFile(Path.Combine(scan.RepositoryRoot, PipelineFileName), Pipeline(scan, settings));
        yield return new GeneratedFile(
            Path.Combine(scan.RepositoryRoot, TemplateFolder.Replace('/', Path.DirectorySeparatorChar), BuildTemplateFileName),
            BuildTemplate());
    }

    private static string Pipeline(ScanResult scan, GenerationSettings settings)
    {
        var hasTests = scan.Projects.Any(static project => project.IsTestProject);
        var sdkVersion = scan.Containerizable
            .Select(static project => project.FrameworkVersion)
            .OfType<string>()
            .OrderByDescending(static version => version, StringComparer.Ordinal)
            .FirstOrDefault() ?? "8.0";

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by dotnet-containerize.");
        builder.AppendLine($"# Builds every containerizable project of {scan.Name} into a container image");
        builder.AppendLine("# and pushes it to Azure Container Registry.");
        builder.AppendLine("#");
        builder.AppendLine("# Before the first run, create a Docker Registry service connection in");
        builder.AppendLine("# Project settings -> Service connections that points to your registry and");
        builder.AppendLine("# set 'dockerRegistryServiceConnection' and 'containerRegistry' below.");
        builder.AppendLine();
        builder.AppendLine("trigger:");
        builder.AppendLine("  branches:");
        builder.AppendLine("    include:");
        builder.AppendLine("      - main");
        builder.AppendLine();
        builder.AppendLine("pr:");
        builder.AppendLine("  branches:");
        builder.AppendLine("    include:");
        builder.AppendLine("      - main");
        builder.AppendLine();
        builder.AppendLine("variables:");
        builder.AppendLine($"  dockerRegistryServiceConnection: '{settings.ServiceConnection}'");
        builder.AppendLine($"  containerRegistry: '{settings.Registry}'");
        builder.AppendLine($"  imagePrefix: '{settings.ImagePrefix}'");
        builder.AppendLine("  tag: '$(Build.BuildNumber)'");
        builder.AppendLine($"  vmImageName: '{settings.VmImage}'");
        builder.AppendLine("  buildConfiguration: 'Release'");
        builder.AppendLine($"  dotnetVersion: '{sdkVersion}.x'");
        builder.AppendLine();
        builder.AppendLine("stages:");
        builder.AppendLine("  - stage: Build");
        builder.AppendLine("    displayName: Build and push container images");
        builder.AppendLine("    jobs:");

        if (hasTests)
        {
            builder.AppendLine("      - job: Test");
            builder.AppendLine("        displayName: Build and test the solution");
            builder.AppendLine("        pool:");
            builder.AppendLine("          vmImage: $(vmImageName)");
            builder.AppendLine("        steps:");
            builder.AppendLine("          - task: UseDotNet@2");
            builder.AppendLine("            displayName: Install the .NET SDK");
            builder.AppendLine("            inputs:");
            builder.AppendLine("              packageType: sdk");
            builder.AppendLine("              version: $(dotnetVersion)");
            builder.AppendLine("          - task: DotNetCoreCLI@2");
            builder.AppendLine("            displayName: dotnet test");
            builder.AppendLine("            inputs:");
            builder.AppendLine("              command: test");
            builder.AppendLine($"              projects: '{TestProjectPattern(scan)}'");
            builder.AppendLine("              arguments: '--configuration $(buildConfiguration)'");
            builder.AppendLine();
        }

        foreach (var project in scan.Containerizable)
        {
            builder.AppendLine($"      - template: {TemplateFolder}/{BuildTemplateFileName}");
            builder.AppendLine("        parameters:");
            builder.AppendLine($"          name: {JobName(project)}");
            builder.AppendLine($"          displayName: {project.Name}");
            builder.AppendLine($"          repository: $(imagePrefix)/{project.ComponentName}");
            builder.AppendLine($"          dockerfile: {DockerfileRelativePath(project, scan)}");
            builder.AppendLine($"          buildContext: {BuildContext(scan)}");
            if (hasTests)
            {
                builder.AppendLine("          dependsOn:");
                builder.AppendLine("            - Test");
            }

            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static string BuildTemplate() => """
        # Generated by dotnet-containerize.
        # Builds a single project into a container image and pushes it to Azure Container Registry.
        # The image is only pushed for builds of the default branch, pull request builds stop at the build.

        parameters:
          - name: name
            type: string
          - name: displayName
            type: string
          - name: repository
            type: string
          - name: dockerfile
            type: string
          - name: buildContext
            type: string
            default: '.'
          - name: dependsOn
            type: object
            default: []

        jobs:
          - job: ${{ parameters.name }}
            displayName: ${{ parameters.displayName }}
            dependsOn: ${{ parameters.dependsOn }}
            pool:
              vmImage: $(vmImageName)
            steps:
              - task: Docker@2
                displayName: Build ${{ parameters.repository }}
                condition: eq(variables['Build.Reason'], 'PullRequest')
                inputs:
                  command: build
                  repository: ${{ parameters.repository }}
                  dockerfile: ${{ parameters.dockerfile }}
                  buildContext: ${{ parameters.buildContext }}
                  containerRegistry: $(dockerRegistryServiceConnection)
                  tags: |
                    $(tag)

              - task: Docker@2
                displayName: Build and push ${{ parameters.repository }}
                condition: ne(variables['Build.Reason'], 'PullRequest')
                inputs:
                  command: buildAndPush
                  repository: ${{ parameters.repository }}
                  dockerfile: ${{ parameters.dockerfile }}
                  buildContext: ${{ parameters.buildContext }}
                  containerRegistry: $(dockerRegistryServiceConnection)
                  tags: |
                    $(tag)
                    latest

        """;

    /// <summary>Azure DevOps job names allow letters, digits and underscores only.</summary>
    internal static string JobName(ProjectInfo project) =>
        "build_" + project.ComponentName.Replace('-', '_');

    /// <summary>Pipeline paths are relative to the repository root, that is where the agent checks out.</summary>
    private static string DockerfileRelativePath(ProjectInfo project, ScanResult scan) =>
        Paths.RelativeTo(scan.RepositoryRoot, DockerfileGenerator.DockerfilePath(project));

    /// <summary>The Docker build context, as a path below the checkout folder.</summary>
    internal static string BuildContext(ScanResult scan) =>
        Paths.RelativeTo(scan.RepositoryRoot, scan.ContextRoot) is var relative && relative == "."
            ? "$(Build.SourcesDirectory)"
            : $"$(Build.SourcesDirectory)/{relative}";

    private static string TestProjectPattern(ScanResult scan) =>
        scan.PrimarySolutionPath is { } solution
            ? Paths.RelativeTo(scan.RepositoryRoot, solution)
            : "**/*Tests/*.csproj";
}
