using System.Text;
using DotnetContainerizer.Model;
using DotnetContainerizer.Scanning;

namespace DotnetContainerizer.Generation;

/// <summary>
/// Produces the same kind of multi stage Dockerfile that Visual Studio adds when
/// "Container support" is enabled for a project. The build context is the solution folder.
/// </summary>
internal static class DockerfileGenerator
{
    private const string WindowsTagSuffix = "-nanoserver-ltsc2022";

    public static GeneratedFile Generate(ProjectInfo project, ScanResult scan, ContainerOs os)
    {
        ArgumentNullException.ThrowIfNull(project);

        var version = project.FrameworkVersion
            ?? throw new InvalidOperationException($"Project '{project.Name}' has no supported target framework.");
        var suffix = os == ContainerOs.Windows ? WindowsTagSuffix : string.Empty;
        var runtimeImage = project.Kind == ContainerKind.AspNet ? "aspnet" : "runtime";
        var projectFile = Path.GetFileName(project.FullPath);
        var projectDirectory = GetDirectory(project.RelativePath);

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by dotnet-containerize.");
        builder.AppendLine("# See https://aka.ms/customizecontainer to learn how to customize this container.");
        builder.AppendLine($"# Build it from the folder holding {scan.Name}:");
        builder.AppendLine($"#   docker build -f {Paths.RelativeTo(scan.ContextRoot, DockerfilePath(project))} -t {project.ComponentName} .");
        builder.AppendLine();

        builder.AppendLine($"FROM mcr.microsoft.com/dotnet/{runtimeImage}:{version}{suffix} AS base");
        if (os == ContainerOs.Linux && project.FrameworkMajorVersion >= 8)
        {
            // $APP_UID is defined by the .NET 8+ base images and runs the app as a non root user.
            builder.AppendLine("USER $APP_UID");
        }

        builder.AppendLine("WORKDIR /app");
        if (project.HttpPort is { } httpPort)
        {
            builder.AppendLine($"EXPOSE {httpPort}");
        }

        if (project.HttpsPort is { } httpsPort)
        {
            builder.AppendLine($"EXPOSE {httpsPort}");
        }

        builder.AppendLine();
        builder.AppendLine($"FROM mcr.microsoft.com/dotnet/sdk:{version}{suffix} AS build");
        builder.AppendLine("ARG BUILD_CONFIGURATION=Release");
        builder.AppendLine("WORKDIR /src");
        foreach (var reference in RestoreOrder(project, scan))
        {
            builder.AppendLine($"COPY [\"{reference}\", \"{GetDirectory(reference)}/\"]");
        }

        builder.AppendLine($"RUN dotnet restore \"{project.RelativePath}\"");
        builder.AppendLine("COPY . .");
        builder.AppendLine($"WORKDIR \"/src/{projectDirectory}\"");
        builder.AppendLine($"RUN dotnet build \"{projectFile}\" -c $BUILD_CONFIGURATION -o /app/build");
        builder.AppendLine();
        builder.AppendLine("FROM build AS publish");
        builder.AppendLine("ARG BUILD_CONFIGURATION=Release");
        builder.AppendLine($"RUN dotnet publish \"{projectFile}\" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false");
        builder.AppendLine();
        builder.AppendLine("FROM base AS final");
        builder.AppendLine("WORKDIR /app");
        builder.AppendLine("COPY --from=publish /app/publish .");
        builder.AppendLine($"ENTRYPOINT [\"dotnet\", \"{project.AssemblyName}.dll\"]");

        return new GeneratedFile(DockerfilePath(project), builder.ToString());
    }

    /// <summary>Visual Studio puts the Dockerfile next to the project file.</summary>
    public static string DockerfilePath(ProjectInfo project) => Path.Combine(project.Directory, "Dockerfile");

    /// <summary>
    /// The project file and its referenced project files, so that <c>dotnet restore</c> runs in its own
    /// cached layer before the rest of the sources are copied.
    /// </summary>
    private static IEnumerable<string> RestoreOrder(ProjectInfo project, ScanResult scan)
    {
        var byPath = scan.Projects.ToDictionary(static item => item.FullPath, StringComparer.OrdinalIgnoreCase);
        var visited = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var ordered = new List<string>();

        void Visit(ProjectInfo current)
        {
            if (!visited.Add(current.FullPath))
            {
                return;
            }

            ordered.Add(current.RelativePath);
            foreach (var reference in current.ProjectReferences)
            {
                if (byPath.TryGetValue(reference, out var referenced))
                {
                    Visit(referenced);
                }
                else if (File.Exists(reference))
                {
                    var relative = Paths.RelativeTo(scan.ContextRoot, reference);
                    if (!relative.StartsWith("..", StringComparison.Ordinal) && visited.Add(reference))
                    {
                        ordered.Add(relative);
                    }
                }
            }
        }

        Visit(project);

        // Projects outside the build context cannot be copied, the context root would not contain them.
        return ordered.Where(static path => !path.StartsWith("..", StringComparison.Ordinal));
    }

    private static string GetDirectory(string relativePath)
    {
        var index = relativePath.LastIndexOf('/');
        return index < 0 ? "." : relativePath[..index];
    }
}
