using DotnetContainerizer.Model;

namespace DotnetContainerizer.Generation;

/// <summary>Creates the .dockerignore file Visual Studio places next to the solution.</summary>
internal static class DockerIgnoreGenerator
{
    private const string Content = """
        # Generated by dotnet-containerize.
        **/.classpath
        **/.dockerignore
        **/.env
        **/.git
        **/.gitignore
        **/.project
        **/.settings
        **/.toolstarget
        **/.vs
        **/.vscode
        **/.idea
        **/*.*proj.user
        **/*.dbmdl
        **/*.jfm
        **/azds.yaml
        **/bin
        **/charts
        **/docker-compose*
        **/Dockerfile*
        **/node_modules
        **/npm-debug.log
        **/obj
        **/secrets.dev.yaml
        **/values.dev.yaml
        **/TestResults
        LICENSE
        README.md

        """;

    public static GeneratedFile Generate(ScanResult scan) =>
        new(Path.Combine(scan.ContextRoot, ".dockerignore"), Content);
}
