using System.Text;
using DotnetContainerizer.Model;

namespace DotnetContainerizer.Generation;

/// <summary>
/// Writes a Helm chart that deploys every containerizable project of the solution. The chart has one
/// generic set of templates and a <c>components</c> map in values.yaml, one entry per project, so adding
/// a project later only means adding a block to values.yaml.
/// </summary>
internal static class HelmChartGenerator
{
    public const string ChartFolder = "helm";

    public static IEnumerable<GeneratedFile> Generate(ScanResult scan, GenerationSettings settings)
    {
        var root = Path.Combine(scan.RepositoryRoot, ChartFolder, settings.ChartName);

        yield return new GeneratedFile(Path.Combine(root, "Chart.yaml"), ChartYaml(scan, settings));
        yield return new GeneratedFile(Path.Combine(root, "values.yaml"), ValuesYaml(scan, settings));
        yield return new GeneratedFile(Path.Combine(root, ".helmignore"), HelmIgnore);
        yield return new GeneratedFile(Path.Combine(root, "templates", "_helpers.tpl"), Helpers);
        yield return new GeneratedFile(Path.Combine(root, "templates", "serviceaccount.yaml"), ServiceAccount);
        yield return new GeneratedFile(Path.Combine(root, "templates", "deployment.yaml"), Deployment);
        yield return new GeneratedFile(Path.Combine(root, "templates", "service.yaml"), Service);
        yield return new GeneratedFile(Path.Combine(root, "templates", "ingress.yaml"), Ingress);
        yield return new GeneratedFile(Path.Combine(root, "templates", "networkpolicy.yaml"), NetworkPolicy);
        yield return new GeneratedFile(Path.Combine(root, "templates", "NOTES.txt"), Notes);
    }

    private static string ChartYaml(ScanResult scan, GenerationSettings settings) => $"""
        # Generated by dotnet-containerize.
        apiVersion: v2
        name: {settings.ChartName}
        description: Deploys the components of the {scan.Name} solution.
        type: application

        # Version of the chart itself, bump it when the templates change.
        version: 0.1.0

        # Default container image tag, override it per deployment with --set image.tag=...
        appVersion: "latest"

        """;

    private static string Boolean(bool value) => value ? "true" : "false";

    private static string ValuesYaml(ScanResult scan, GenerationSettings settings)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by dotnet-containerize.");
        builder.AppendLine("# One entry per component of the solution, see the components section at the bottom.");
        builder.AppendLine();
        builder.AppendLine("image:");
        builder.AppendLine("  # Login server of the Azure Container Registry.");
        builder.AppendLine($"  registry: {settings.Registry}");
        builder.AppendLine("  # Repository prefix, the image becomes <registry>/<prefix>/<repository>:<tag>.");
        builder.AppendLine($"  prefix: {settings.ImagePrefix}");
        builder.AppendLine("  # Overridden by the pipeline with --set image.tag=$(Build.BuildNumber).");
        builder.AppendLine("  tag: \"\"");
        builder.AppendLine("  pullPolicy: IfNotPresent");
        builder.AppendLine("  # Pull secrets for a private registry, not needed when the cluster is attached to the ACR.");
        builder.AppendLine("  pullSecrets: []");
        builder.AppendLine("  #  - name: acr-pull-secret");
        builder.AppendLine();
        builder.AppendLine("nameOverride: \"\"");
        builder.AppendLine("fullnameOverride: \"\"");
        builder.AppendLine();
        builder.AppendLine("serviceAccount:");
        builder.AppendLine("  create: true");
        builder.AppendLine("  name: \"\"");
        builder.AppendLine("  annotations: {}");
        if (settings.Hardened)
        {
            builder.AppendLine("  # The components do not talk to the Kubernetes API, so they get no token.");
        }

        builder.AppendLine($"  automountServiceAccountToken: {Boolean(!settings.Hardened)}");
        builder.AppendLine();
        builder.AppendLine("podAnnotations: {}");
        builder.AppendLine("podLabels: {}");
        builder.AppendLine();
        builder.AppendLine("# Pod level hardening, applies to every component.");
        builder.AppendLine("podSecurityContext:");
        builder.AppendLine("  runAsNonRoot: true");
        if (settings.Hardened)
        {
            builder.AppendLine("  seccompProfile:");
            builder.AppendLine("    type: RuntimeDefault");
        }

        builder.AppendLine();
        builder.AppendLine("# Container level hardening, applies to every component.");
        builder.AppendLine("securityContext:");
        builder.AppendLine("  allowPrivilegeEscalation: false");
        builder.AppendLine("  privileged: false");
        if (settings.Hardened)
        {
            builder.AppendLine("  # /tmp is mounted as an emptyDir so the app still has somewhere to write.");
        }

        builder.AppendLine($"  readOnlyRootFilesystem: {Boolean(settings.Hardened)}");
        builder.AppendLine("  capabilities:");
        builder.AppendLine("    drop:");
        builder.AppendLine("      - ALL");
        builder.AppendLine();
        builder.AppendLine("# Denies traffic that does not come from the ingress controller or the release itself.");
        builder.AppendLine("# Off by default because it needs a CNI plugin that enforces network policies.");
        builder.AppendLine("networkPolicy:");
        builder.AppendLine("  enabled: false");
        builder.AppendLine("  ingressNamespace: ingress-nginx");
        builder.AppendLine();
        builder.AppendLine("nodeSelector: {}");
        builder.AppendLine("tolerations: []");
        builder.AppendLine("affinity: {}");
        builder.AppendLine();
        builder.AppendLine("components:");

        foreach (var project in scan.Containerizable)
        {
            AppendComponent(builder, project, settings);
        }

        return builder.ToString();
    }

    private static void AppendComponent(StringBuilder builder, ProjectInfo project, GenerationSettings settings)
    {
        var isWeb = project.Kind == ContainerKind.AspNet;
        var httpPort = ContainerPorts.Http(project, settings.Hardened);
        builder.AppendLine($"  # {project.Name} ({(isWeb ? "ASP.NET Core" : "console/worker")}, {project.TargetFramework})");
        builder.AppendLine($"  {project.ComponentName}:");
        builder.AppendLine("    enabled: true");
        builder.AppendLine($"    repository: {project.ComponentName}");
        builder.AppendLine("    # tag: \"\"  # overrides image.tag for this component only");
        builder.AppendLine($"    replicaCount: {(isWeb ? 2 : 1)}");
        builder.AppendLine("    env:");
        builder.AppendLine("      - name: DOTNET_ENVIRONMENT");
        builder.AppendLine("        value: Production");

        if (isWeb)
        {
            builder.AppendLine("      - name: ASPNETCORE_ENVIRONMENT");
            builder.AppendLine("        value: Production");
            var portVariable = ContainerPorts.UrlEnvironmentVariable(project, settings.Hardened);
            builder.AppendLine($"      - name: {portVariable?.Name ?? "ASPNETCORE_HTTP_PORTS"}");
            builder.AppendLine($"        value: \"{portVariable?.Value ?? httpPort?.ToString()}\"");
            builder.AppendLine("    envFrom: []");
            builder.AppendLine($"    containerPort: {httpPort}");
            builder.AppendLine("    service:");
            builder.AppendLine("      enabled: true");
            builder.AppendLine("      type: ClusterIP");
            builder.AppendLine("      port: 80");
            builder.AppendLine("      annotations: {}");
            builder.AppendLine("    ingress:");
            builder.AppendLine("      enabled: false");
            builder.AppendLine("      className: \"\"");
            builder.AppendLine("      annotations: {}");
            builder.AppendLine("      hosts:");
            builder.AppendLine($"        - host: {project.ComponentName}.example.com");
            builder.AppendLine("          paths:");
            builder.AppendLine("            - path: /");
            builder.AppendLine("              pathType: Prefix");
            builder.AppendLine("      tls: []");
            builder.AppendLine("    # Enable once the application serves a health endpoint.");
            builder.AppendLine("    probes:");
            builder.AppendLine("      enabled: false");
            builder.AppendLine("      path: /healthz");
        }
        else
        {
            builder.AppendLine("    envFrom: []");
            builder.AppendLine("    service:");
            builder.AppendLine("      enabled: false");
            builder.AppendLine("    ingress:");
            builder.AppendLine("      enabled: false");
            builder.AppendLine("    probes:");
            builder.AppendLine("      enabled: false");
        }

        builder.AppendLine("    resources:");
        builder.AppendLine("      requests:");
        builder.AppendLine("        cpu: 50m");
        builder.AppendLine("        memory: 128Mi");
        builder.AppendLine("      limits:");
        builder.AppendLine("        memory: 512Mi");
        builder.AppendLine();
    }

    private const string HelmIgnore = """
        # Generated by dotnet-containerize.
        .DS_Store
        .git/
        .gitignore
        .idea/
        .vs/
        .vscode/
        *.tgz
        *.tmproj

        """;

    private const string Helpers = """
        {{/* Generated by dotnet-containerize. */}}

        {{/* Chart name, overridable with nameOverride. */}}
        {{- define "solution.name" -}}
        {{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
        {{- end -}}

        {{/* Release wide name prefix, overridable with fullnameOverride. */}}
        {{- define "solution.fullname" -}}
        {{- if .Values.fullnameOverride -}}
        {{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
        {{- else -}}
        {{- $name := default .Chart.Name .Values.nameOverride -}}
        {{- if contains $name .Release.Name -}}
        {{- .Release.Name | trunc 63 | trimSuffix "-" -}}
        {{- else -}}
        {{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
        {{- end -}}
        {{- end -}}
        {{- end -}}

        {{/* Name of a single component, takes a dict with root and name. */}}
        {{- define "solution.componentName" -}}
        {{- $fullname := include "solution.fullname" .root -}}
        {{- $chart := include "solution.name" .root -}}
        {{- $name := .name -}}
        {{- if hasPrefix (printf "%s-" $chart) $name -}}
        {{- $name = trimPrefix (printf "%s-" $chart) $name -}}
        {{- end -}}
        {{- if hasPrefix $fullname $name -}}
        {{- $name | trunc 63 | trimSuffix "-" -}}
        {{- else -}}
        {{- printf "%s-%s" $fullname $name | trunc 63 | trimSuffix "-" -}}
        {{- end -}}
        {{- end -}}

        {{- define "solution.chart" -}}
        {{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
        {{- end -}}

        {{/* Labels shared by every object of the release. */}}
        {{- define "solution.labels" -}}
        helm.sh/chart: {{ include "solution.chart" .root }}
        app.kubernetes.io/name: {{ include "solution.name" .root }}
        app.kubernetes.io/instance: {{ .root.Release.Name }}
        app.kubernetes.io/component: {{ .name }}
        app.kubernetes.io/managed-by: {{ .root.Release.Service }}
        {{- with .root.Chart.AppVersion }}
        app.kubernetes.io/version: {{ . | quote }}
        {{- end }}
        {{- end -}}

        {{/* Labels a component selects its pods with. */}}
        {{- define "solution.selectorLabels" -}}
        app.kubernetes.io/name: {{ include "solution.name" .root }}
        app.kubernetes.io/instance: {{ .root.Release.Name }}
        app.kubernetes.io/component: {{ .name }}
        {{- end -}}

        {{/* Full image reference of a component, takes a dict with root, name and component. */}}
        {{- define "solution.image" -}}
        {{- $registry := .root.Values.image.registry | trimSuffix "/" -}}
        {{- $prefix := .root.Values.image.prefix | default "" -}}
        {{- $repository := .component.repository | default .name -}}
        {{- $tag := .component.tag | default .root.Values.image.tag | default .root.Chart.AppVersion | default "latest" -}}
        {{- $path := $repository -}}
        {{- if $prefix -}}
        {{- $path = printf "%s/%s" $prefix $repository -}}
        {{- end -}}
        {{- if $registry -}}
        {{- printf "%s/%s:%s" $registry $path $tag -}}
        {{- else -}}
        {{- printf "%s:%s" $path $tag -}}
        {{- end -}}
        {{- end -}}

        {{- define "solution.serviceAccountName" -}}
        {{- if .Values.serviceAccount.create -}}
        {{- default (include "solution.fullname" .) .Values.serviceAccount.name -}}
        {{- else -}}
        {{- default "default" .Values.serviceAccount.name -}}
        {{- end -}}
        {{- end -}}

        """;

    private const string ServiceAccount = """
        {{/* Generated by dotnet-containerize. */}}
        {{- if .Values.serviceAccount.create -}}
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: {{ include "solution.serviceAccountName" . }}
          labels:
            {{- include "solution.labels" (dict "root" $ "name" "shared") | nindent 4 }}
          {{- with .Values.serviceAccount.annotations }}
          annotations:
            {{- toYaml . | nindent 4 }}
          {{- end }}
        automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default false }}
        {{- end }}

        """;

    private const string Deployment = """
        {{/* Generated by dotnet-containerize. One Deployment per enabled component. */}}
        {{- $root := . -}}
        {{- range $name, $component := .Values.components }}
        {{- if $component.enabled }}
        ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {{ include "solution.componentName" (dict "root" $root "name" $name) }}
          labels:
            {{- include "solution.labels" (dict "root" $root "name" $name) | nindent 4 }}
        spec:
          replicas: {{ $component.replicaCount | default 1 }}
          selector:
            matchLabels:
              {{- include "solution.selectorLabels" (dict "root" $root "name" $name) | nindent 6 }}
          template:
            metadata:
              labels:
                {{- include "solution.selectorLabels" (dict "root" $root "name" $name) | nindent 8 }}
                {{- with $root.Values.podLabels }}
                {{- toYaml . | nindent 8 }}
                {{- end }}
              {{- with $root.Values.podAnnotations }}
              annotations:
                {{- toYaml . | nindent 8 }}
              {{- end }}
            spec:
              {{- with $root.Values.image.pullSecrets }}
              imagePullSecrets:
                {{- toYaml . | nindent 8 }}
              {{- end }}
              serviceAccountName: {{ include "solution.serviceAccountName" $root }}
              automountServiceAccountToken: {{ $root.Values.serviceAccount.automountServiceAccountToken | default false }}
              {{- with $root.Values.podSecurityContext }}
              securityContext:
                {{- toYaml . | nindent 8 }}
              {{- end }}
              containers:
                - name: {{ $name }}
                  image: {{ include "solution.image" (dict "root" $root "name" $name "component" $component) | quote }}
                  imagePullPolicy: {{ $root.Values.image.pullPolicy }}
                  {{- with $root.Values.securityContext }}
                  securityContext:
                    {{- toYaml . | nindent 12 }}
                  {{- end }}
                  {{- with $component.containerPort }}
                  ports:
                    - name: http
                      containerPort: {{ . }}
                      protocol: TCP
                  {{- end }}
                  {{- with $component.env }}
                  env:
                    {{- toYaml . | nindent 12 }}
                  {{- end }}
                  {{- with $component.envFrom }}
                  envFrom:
                    {{- toYaml . | nindent 12 }}
                  {{- end }}
                  {{- if and $component.probes $component.probes.enabled }}
                  livenessProbe:
                    httpGet:
                      path: {{ $component.probes.path | default "/healthz" }}
                      port: http
                    initialDelaySeconds: {{ $component.probes.initialDelaySeconds | default 10 }}
                    periodSeconds: {{ $component.probes.periodSeconds | default 10 }}
                  readinessProbe:
                    httpGet:
                      path: {{ $component.probes.readinessPath | default $component.probes.path | default "/healthz" }}
                      port: http
                    initialDelaySeconds: {{ $component.probes.initialDelaySeconds | default 5 }}
                    periodSeconds: {{ $component.probes.periodSeconds | default 10 }}
                  {{- end }}
                  {{- with $component.resources }}
                  resources:
                    {{- toYaml . | nindent 12 }}
                  {{- end }}
                  {{- if or $root.Values.securityContext.readOnlyRootFilesystem $component.volumeMounts }}
                  volumeMounts:
                    {{- if $root.Values.securityContext.readOnlyRootFilesystem }}
                    {{/* .NET writes temporary files, so a writable /tmp is needed. */}}
                    - name: tmp
                      mountPath: /tmp
                    {{- end }}
                    {{- with $component.volumeMounts }}
                    {{- toYaml . | nindent 12 }}
                    {{- end }}
                  {{- end }}
              {{- if or $root.Values.securityContext.readOnlyRootFilesystem $component.volumes }}
              volumes:
                {{- if $root.Values.securityContext.readOnlyRootFilesystem }}
                - name: tmp
                  emptyDir: {}
                {{- end }}
                {{- with $component.volumes }}
                {{- toYaml . | nindent 8 }}
                {{- end }}
              {{- end }}
              {{- with $root.Values.nodeSelector }}
              nodeSelector:
                {{- toYaml . | nindent 8 }}
              {{- end }}
              {{- with $root.Values.tolerations }}
              tolerations:
                {{- toYaml . | nindent 8 }}
              {{- end }}
              {{- with $root.Values.affinity }}
              affinity:
                {{- toYaml . | nindent 8 }}
              {{- end }}
        {{- end }}
        {{- end }}

        """;

    private const string Service = """
        {{/* Generated by dotnet-containerize. One Service per component that listens on a port. */}}
        {{- $root := . -}}
        {{- range $name, $component := .Values.components }}
        {{- if and $component.enabled $component.service $component.service.enabled }}
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: {{ include "solution.componentName" (dict "root" $root "name" $name) }}
          labels:
            {{- include "solution.labels" (dict "root" $root "name" $name) | nindent 4 }}
          {{- with $component.service.annotations }}
          annotations:
            {{- toYaml . | nindent 4 }}
          {{- end }}
        spec:
          type: {{ $component.service.type | default "ClusterIP" }}
          selector:
            {{- include "solution.selectorLabels" (dict "root" $root "name" $name) | nindent 4 }}
          ports:
            - name: http
              port: {{ $component.service.port | default 80 }}
              targetPort: http
              protocol: TCP
        {{- end }}
        {{- end }}

        """;

    private const string Ingress = """
        {{/* Generated by dotnet-containerize. One Ingress per component that asks for one. */}}
        {{- $root := . -}}
        {{- range $name, $component := .Values.components }}
        {{- if and $component.enabled $component.ingress $component.ingress.enabled }}
        ---
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: {{ include "solution.componentName" (dict "root" $root "name" $name) }}
          labels:
            {{- include "solution.labels" (dict "root" $root "name" $name) | nindent 4 }}
          {{- with $component.ingress.annotations }}
          annotations:
            {{- toYaml . | nindent 4 }}
          {{- end }}
        spec:
          {{- with $component.ingress.className }}
          ingressClassName: {{ . }}
          {{- end }}
          {{- with $component.ingress.tls }}
          tls:
            {{- toYaml . | nindent 4 }}
          {{- end }}
          rules:
            {{- range $component.ingress.hosts }}
            - host: {{ .host | quote }}
              http:
                paths:
                  {{- range .paths }}
                  - path: {{ .path }}
                    pathType: {{ .pathType | default "Prefix" }}
                    backend:
                      service:
                        name: {{ include "solution.componentName" (dict "root" $root "name" $name) }}
                        port:
                          number: {{ $component.service.port | default 80 }}
                  {{- end }}
            {{- end }}
        {{- end }}
        {{- end }}

        """;

    private const string NetworkPolicy = """
        {{/* Generated by dotnet-containerize. Opt in, it needs a CNI plugin that enforces policies. */}}
        {{- $root := . -}}
        {{- if .Values.networkPolicy.enabled }}
        {{- range $name, $component := .Values.components }}
        {{- if $component.enabled }}
        ---
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: {{ include "solution.componentName" (dict "root" $root "name" $name) }}
          labels:
            {{- include "solution.labels" (dict "root" $root "name" $name) | nindent 4 }}
        spec:
          podSelector:
            matchLabels:
              {{- include "solution.selectorLabels" (dict "root" $root "name" $name) | nindent 6 }}
          policyTypes:
            - Ingress
          ingress:
            {{- if and $component.service $component.service.enabled }}
            {{/* Pods of this release and the ingress controller may reach the component. */}}
            - from:
                - podSelector:
                    matchLabels:
                      app.kubernetes.io/instance: {{ $root.Release.Name }}
                {{- with $root.Values.networkPolicy.ingressNamespace }}
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: {{ . }}
                {{- end }}
              ports:
                - port: {{ $component.containerPort | default 8080 }}
                  protocol: TCP
            {{- else }}
            {{/* Workers accept no inbound traffic at all. */}}
            []
            {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}

        """;

    private const string Notes = """
        {{/* Generated by dotnet-containerize. */}}
        {{ .Chart.Name }} {{ .Chart.Version }} is deployed as release {{ .Release.Name }} in namespace {{ .Release.Namespace }}.

        Components:
        {{- range $name, $component := .Values.components }}
        {{- if $component.enabled }}
          - {{ $name }}: {{ include "solution.image" (dict "root" $ "name" $name "component" $component) }}
        {{- end }}
        {{- end }}

        Check the rollout with:
          kubectl get deployments -n {{ .Release.Namespace }} -l app.kubernetes.io/instance={{ .Release.Name }}

        {{- range $name, $component := .Values.components }}
        {{- if and $component.enabled $component.service $component.service.enabled }}
        Reach {{ $name }} from inside the cluster at:
          http://{{ include "solution.componentName" (dict "root" $ "name" $name) }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $component.service.port | default 80 }}
        {{- end }}
        {{- end }}

        """;
}
